language: python

sudo: required

before_install:
  - sudo apt-get -qq update
  - pip install --upgrade google-api-python-client

install:
  - sudo apt-get install libjpeg8-dev libtiff4-dev libjasper-dev libpng12-dev
  - sudo apt-get install python-dev python-numpy
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git checkout 3.0.0
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_C_EXAMPLES=ON \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
    -D BUILD_EXAMPLES=ON ..
  - make -j4
  - cd ../../
  - sudo apt-get install autoconf automake libtool
  - sudo apt-get install libpng12-dev
  - sudo apt-get install libjpeg62-dev
  - sudo apt-get install libtiff4-dev
  - sudo apt-get install zlib1g-dev
  - sudo apt-get install libleptonica-dev
  - sudo apt-get install libtesseract-dev
  - sudo apt-get install tesseract
  - "pip install -r requirements.txt"

python:
  - "2.7"

script:
  - ./test_flask.sh
