language: python

sudo: required
dist: trusty

before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu/ wily universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - pip install --upgrade google-api-python-client
  

install:
  - sudo apt-get install -y libjpeg8-dev libtiff4-dev libjasper-dev libpng12-dev
  - sudo apt-get install -y python-dev python-numpy
  - sudo apt-get install -y autoconf automake libtool
  - sudo apt-get install -y libpng12-dev
  - sudo apt-get install -y libjpeg62-dev
  - sudo apt-get install -y libtiff4-dev
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y libleptonica-dev
  - sudo apt-get install -y libtesseract-dev
  - sudo apt-get install -y tesseract-ocr
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git checkout 3.0.0
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_C_EXAMPLES=ON \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
    -D BUILD_EXAMPLES=ON ..
  - make -j4
  - cd ../../
  - "pip install -r requirements.txt"

python:
  - "2.7"

script:
  - ./test_flask.sh
