language: python

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install opencv-python

install:
  "pip install -r requirements.txt"

python:
  - "2.7"

script:
  - "py.test application/tests/*.py "
