"""Upgrading the notes tables with the id and image_path

Revision ID: 4063b5ae57b8
Revises: 00d6fc184a31
Create Date: 2016-02-29 18:41:49.525586

"""

# revision identifiers, used by Alembic.
revision = '4063b5ae57b8'
down_revision = '00d6fc184a31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'notes_pkey')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')

    ### end Alembic commands ###
